_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 63
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 63
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.15
            "5": 0.18.5
            "6": 4.45.2
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
architecture:
    value: CLIP
dataset:
    value: HICO-DET
epochs:
    value: 1
learning_rate:
    value: 1e-05
